askcompany/askcompany/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings # setting는 이렇게 접근해야 함
from django.views.generic import TemplateView,RedirectView

# class RootView(TemplateView):
#     template_name = 'root.html'

urlpatterns = [
    # path('',TemplateView.as_view(template_name='root.html'),name='root'),
    path('',RedirectView.as_view(
        # url = '/instagram/'
        pattern_name = 'instagram:post_list'
        ),name='root'),
    
    path('admin/', admin.site.urls), # URL Reverse는 admin주소 바꿔서 알아서 찾아감
    path('blog1/',include('blog1.urls')),
    path('k-instagram/',include('instagram.urls')),
    path('accounts/',include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/',include(debug_toolbar.urls)),
    ]

settings.MEDIA_URL
settings.MEDIA_ROOT

askcompany/blog1/urls.py
from . import views
from django.urls import path

app_name = 'blog1' # URL Reverse 에서 namespace역할을 하게 된다.

urlpatterns = [
    path('',views.post_list,name='post_list'),
]

askcompany/instagram/urls.py
from . import views
from django.urls import path,re_path,register_converter
from django.views.generic import ListView
from .models import Post
from .converters import YearConverter,MonthConverter,DayConverter

class ItemListView(ListView):
    model = Post
    
item_list = ItemListView.as_view()



register_converter(YearConverter,'year')
register_converter(MonthConverter,'month')
register_converter(DayConverter,'day')

app_name = 'instagram' # URL Reverse 에서 namespace역할을 하게 된다.


urlpatterns=[
    path('new/',views.post_new,name='post_new'),
    path('<int:pk>/edit/',views.post_edit,name='post_edit'),
    path('',views.post_list,name='post_list'),
    path('<int:pk>/',views.post_detail,name='post_detail'),
    path('items/',item_list,name='item_list'),

    # path('archives/<int:year>/',views.archives_year),
    # re_path(r'archives/(?P<year>20\d{2})/',views.archives_year),
    path('archive/',views.post_archive,name='post_archive'),
    path('archive/<year:year>/',views.post_archive_year,name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/',views.post_archive_month,name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:day>/',views.post_archive_day,name='post_archive_day'),

]

askcompany/instagram/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from django.urls import reverse




class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True,upload_to='instagram/post/%Y/%m/%d') #/media/instagram/post/
    tag_set = models.ManyToManyField('Tag',blank=True) # m : n 에서는 blank 를 True로 보통해야함 : 태그를 안하는 경우도 있으니까 => 장고 유효성 검사에서 걸림
    is_public = models.BooleanField(default=False,verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        # return f"Custom Post object ({self.id})"
        return self.message
    
    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])

    class Meta:
        ordering = ['-id']
        # unique_together = [
        #     ('server','username')
        # ] => 유니크하게 DB에 넣고 싶을 때

    # Java의 toString
    
    
    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = '메세지 글자수'

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,
                                limit_choices_to={'is_public':True}) #instagram.Post    => post_id 필드가 생성이 됩니다.
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=50,unique=True)
    # post_set = models.ManyToManyField(Post) 혹은

    def __str__(self):
        return self.name

askcompany/instagram/forms.py
from  django import forms
from .models import Post
import re

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'message','photo','tag_set','is_public'
        ]
        # exclude = 
    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message:
            message = re.sub(r'[a-zA-Z]+','',message)
        return message

askcompany/instagram/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView,DetailView,ArchiveIndexView,YearArchiveView,MonthArchiveView,DayArchiveView,TodayArchiveView
from django.shortcuts import render,HttpResponse,Http404,get_object_or_404,redirect
from .models import Post
from .forms import PostForm

@login_required
def post_new(request):
    if request.method=='POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user # 현재 로그인 user instance
            post.save()
            return redirect(post)
    else:
        form = PostForm()
    return render(request,'instagram/post_form.html',{
        'form':form,
    })

@login_required
def post_edit(request,pk):
    post = get_object_or_404(Post,pk=pk)

    # 작성자 Check Tip
    if post.author != request.user:
        messages.error(request,'작성자만 수정할 수 있습니다.')
        return redirect(post)

    if request.method=='POST':
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm(instance=post)
    return render(request,'instagram/post_form.html',{
        'form':form,
    })


# /instagram/
# /instagram/1/
# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q','') # 두번째 인자는 없을 때 대신인자
#     if q:
#         qs = qs.filter(message__icontains=q)
#     # instagram/templates/instagram/post_list.html
#     return render(request,'instagram/post_list.html',{
#         'post_list':qs,
#         'q' : q,
#     })

# def post_detail(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     return render(request,'instagram/post_detail.html',{
#         'post':post,
#     })


# post_list = login_required(ListView.as_view(model=Post,paginate_by=10))


# @method_decorator(login_required,name='dispatch')
class PostListView(LoginRequiredMixin,ListView):
    model = Post
    paginate_by = 10
    
post_list = PostListView.as_view()
# post_detail = DetailView.as_view(
#     model=Post,
#     queryset=Post.objects.filter(is_public=True))


# 비 로그인 시 공개된 것만 봐라
class PostDetailView(DetailView):
    model = Post
    # queryset = Post.objects.filter(is_public=True)
    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated: # 로그인 여부
            qs = qs.filter(is_public=True)
        return qs

post_detail = PostDetailView.as_view()

# def archives_year(request,year):
#     return HttpResponse(f"{year}년 archives")

post_archive = ArchiveIndexView.as_view(model=Post,date_field='created_at',paginate_by=10)

post_archive_year = YearArchiveView.as_view(model=Post,date_field='created_at',make_object_list=True)

post_archive_month = MonthArchiveView.as_view(model=Post,date_field='created_at')

post_archive_day = DayArchiveView.as_view(model=Post,date_field='created_at')


# django authentication system (장고 인증 시스템)

askcompany/instagram/templates/instagram/layout.html
{% load static %}
<!DOCTYPE html>
<html lang='ko'>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/simplex/bootstrap.min.css" integrity="sha384-FYrl2Nk72fpV6+l3Bymt1zZhnQFK75ipDqPXK0sOR0f/zeOSZ45/tKlsKucQyjSp" crossorigin="anonymous">
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/darkly/bootstrap.min.css" integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN" crossorigin="anonymous"> -->
        <!-- <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
            crossorigin="anonymous"> -->
        <!-- <script src="http://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> -->
        <link rel='stylesheet' href="{% static 'bootstrap-5.0.0-beta1-dist/css/bootstrap.css' %}">
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'bootstrap-5.0.0-beta1-dist/js/bootstrap.js' %}"></script>
        <style>
           body{
               padding-top:5rem;
               padding-bottom:5rem;
           }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
          
              <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
<div class='container'>
    <div class='row'>
        <div class='col-sm-12'>
            {% block content %}
            {% endblock content %}
            <hr/>
            &copy; 이창현
        </div>
    </div>
</div>
    </body>
</html>

askcompany/instagram/templates/instagram/post_archive.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang='ko'>
    <head></head>
    <body>
        <h2>latest</h2>
        {{ latest }}

        <h2>data_list</h2>
     
        {% for date in date_list %}
            {{ date|date:"Y" }}
            {{ date.year }}
            
        {% endfor %}

    </body>

askcompany/instagram/templates/instagram/post_archive_month.html
<h2>year</h2>
{{ year }}
<br>
<h2>previous_year</h2>
{{ previous_year }}
<br>
<h2>next_year</h2>
{{ next_year }}
<br>
<h2>date_list</h2>
{{ date_list }}
<br>
<h2>object_list</h2>
{{ object_list }}

askcompany/instagram/templates/instagram/post_archive_year.html
<h2>year</h2>
{{ year }}
<br>
<h2>previous_year</h2>
{{ previous_year }}
<br>
<h2>next_year</h2>
{{ next_year }}
<br>
<h2>date_list</h2>
{{ date_list }}
<br>
<h2>object_list</h2>
{{ object_list }}

askcompany/instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}
{% block title %}
    Post Detail pk# {{ post.pk }}
{% endblock title %}
{% block content %}
    <h2>Author :
        {{ post.author }}</h2>

    {% if post.photo %}
        <img src="{{ post.photo.url }}"/>
    {% endif %}
    {{ post.message|linebreaks }}
    <hr/>
    <a href="{% url 'instagram:post_list' %}" class='btn btn-primary'>
        목록
    </a>
    <a href="{% url 'instagram:post_edit' post.pk %}" class='btn btn-info'>수정</a>
{% endblock content %}

askcompany/instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}
{% block title %}
    Instagram / Post form
{% endblock title %}

{% block content %}
    <form action='' method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type='submit' value='저장'>
    </form>
{% endblock content %}

askcompany/instagram/templates/instagram/post_list.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}
{% block content %}
<!-- <script>
    if(1>0){
    alert('hello');
    }
</script> -->
    <body>
        <form action='' method='get'>
            <input type='text' name='q' value='{{ q }}'/>
            <input type='submit' value='검색'>
        </form>
        <a href="{% url 'instagram:post_new' %}" class='btn btn-primary btn-block mt-1 mb-1'>새 포스팅</a>
        <table class='table table-bordered table-hover'>
            <tbody>

                {% for post in post_list %}
                    <tr>
                        <td>
                            {{ post.pk }}
                        </td>
                        <td>
                            {% if post.photo %}
                                <img src='{{ post.photo.url }}' style='width:100px;'/>
                            {% else %}
                                No Photo
                            {% endif %}
                        </td>

                        <td>
                            <!-- <a href="{% url 'instagram:post_detail' post.pk %}"> -->
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.message }}
                            </a>
                                
                            <!-- </a> -->
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
        {% if is_paginated %}
            {% bootstrap_pagination page_obj size='small' justify_content='center' %}
        {% endif %}
    </body>
{% endblock content %}